//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AdVisuo.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDB_BUTTONS                     113
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_AdVisuoTYPE                 130
#define ID_                             130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_OUTPUTWND               150
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_OUTPUT_WND                  157
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_OUTPUT_POPUP                182
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDB_CAMERASMALL                 310
#define IDB_CAMERASMALL1                311
#define IDB_CAMERALARGE                 311
#define IDB_BITMAP1                     312
#define IDB_LOGO                        312
#define IDD_ADV_DOWNLOAD                315
#define IDD_DIALOG1                     316
#define IDD_ADV_VIDEO                   316
#define IDD_ADV_VIDEOCTRL               317
#define IDR_RIBBON1                     318
#define IDR_RIBBON                      318
#define IDR_HTML_SPLASH                 320
#define IDD_ADV_ASPECT                  324
#define IDS_SAVE_OPTION1                331
#define IDS_DLGVIDEO_MESSAGE            331
#define IDS_SAVE_OPTION2                332
#define IDS_DLGVIDEO_TITLE              332
#define IDS_DLGVIDEO_FOOTER             333
#define IDD_ADV_REPORT_BUG              333
#define IDS_DLGVIDEO_INSTR              334
#define IDS_DLGVIDEO_OPTION1            335
#define IDD_ADV_MATERIALS               335
#define IDS_DLGVIDEO_OPTION2            336
#define IDS_DLGVIDEO_MESSAGE2           337
#define IDD_ADV_SCRIPT                  337
#define IDD_ADV_SCRIPT_PROPERTIES       338
#define IDD_ADV_LOGIN                   339
#define IDB_BITMAP3                     340
#define IDB_SCENARIOS                   340
#define IDD_ADV_LOGIN1                  340
#define IDD_ADV_SPLASH                  340
#define IDR_HTML_CSS                    341
#define IDD_ADV_ABOUT                   341
#define IDR_HTML_PNG_HEADER             342
#define IDD_ADV_LOGIN2                  342
#define IDD_ADV_SELECT                  342
#define IDR_HTML_PNG_FORM               343
#define IDR_HTML_PNG_BUTTON             344
#define IDR_HTML_PNG_SPLASH1            345
#define IDR_HTML_PNG_SPLASH2            346
#define IDR_HTML_PNG_CONNECTION         347
#define IDR_HTML_PNG_SPLASH3            348
#define IDR_HTML_PNG_SPLASH4            349
#define IDR_HTML_PNG_WAITMSG            349
#define IDR_HTML_LOGIN                  355
#define IDR_HTML_SPLASH1                356
#define IDR_HTML_ABOUT                  357
#define IDR_HTML_SELECT                 358
#define IDR_XSLT_SELECT_PRJ             359
#define IDR_XSLT_SELECT_SIM             360
#define IDR_MESH_BUFFER                 361
#define IDR_HTML_LOGIN1                 361
#define IDR_HTML_REP                    361
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_EDIT_RESY                   1003
#define IDC_EDIT_TIME_FROM              1004
#define IDC_EDIT_TIME_TO                1005
#define IDC_EDIT_XRES                   1006
#define IDC_EDIT_YRES                   1007
#define IDC_STOP                        1008
#define IDC_STATIC_STATUS               1009
#define IDC_STATIC_TIME                 1010
#define IDC_CHECK1                      1011
#define IDC_CHECK_PREVIEW               1011
#define IDC_CHECK_NO_RATIO              1011
#define IDC_CHECK_RESTRICT              1011
#define IDC_COMBO1                      1012
#define IDC_REFRESH                     1022
#define IDC_LIST1                       1023
#define IDC_DETAILS                     1028
#define IDC_RADIO1                      1029
#define IDC_RADIO2                      1030
#define IDC_RADIO3                      1031
#define IDC_RADIO4                      1032
#define IDC_RADIO5                      1033
#define IDC_RADIO6                      1034
#define IDC_RADIO7                      1035
#define IDC_RADIO_FPS_25P               1035
#define IDC_RADIO8                      1036
#define IDC_RADIO_FPS_30                1036
#define IDC_RADIO9                      1037
#define IDC_RADIO_FPS_50                1037
#define IDC_RADIO10                     1038
#define IDC_RADIO_FPS_60                1038
#define IDC_RADIO_FPS_CUSTOM            1039
#define IDC_SPIN1                       1041
#define IDC_SPIN3                       1043
#define IDC_STATIC_1                    1044
#define IDC_STATIC_2                    1045
#define IDC_CUSTOM                      1047
#define IDC_RADIO_ASPECT_16_9           1049
#define IDC_SWITCH                      1052
#define IDC_REVERT                      1053
#define IDC_FILEPATH                    1056
#define IDC_TIME_BEGIN                  1057
#define IDC_COMBO_RES                   1058
#define IDC_TIME_END                    1059
#define IDC_EDIT_RESX                   1060
#define IDC_RADIO_FPS_25                1061
#define IDC_RADIO_FPS_24                1061
#define IDC_EDIT_FPS                    1062
#define IDC_EDIT_ASPECT                 1063
#define IDC_RADIO_ASPECT_16_10          1065
#define IDC_RADIO_ASPECT_4_3            1066
#define IDC_RADIO_ASPECT_CUSTOM         1067
#define IDC_SPIN2                       1068
#define IDC_CHECK_CAPTIONS              1069
#define IDC_CHECK3                      1070
#define IDC_CHECK_CLOCK                 1070
#define IDC_EDIT_NAME                   1071
#define IDC_EDIT_EMAIL                  1072
#define IDC_COMBO_CAT                   1073
#define IDC_EDIT_DESC                   1074
#define IDC_EDIT_DESC2                  1075
#define IDC_EDIT_SYSTEM                 1075
#define IDC_MFCCOLORBUTTON1             1075
#define IDC_SLIDER1                     1076
#define IDC_BUTTON2                     1079
#define IDC_LIST2                       1081
#define IDC_ADD_EVENT                   1082
#define IDC_REMOVE_EVENT                1083
#define IDC_PLAY_EVENT                  1084
#define IDC_PROPERTIES                  1085
#define IDC_DATETIMEPICKER1             1086
#define IDC_DATETIMEPICKER2             1087
#define IDC_LOAD                        1087
#define IDC_SAVE                        1088
#define IDC_EDIT_USERNAME               1089
#define IDC_DEBUG                       1092
#define IDC_WAIT_MSG                    1099
#define IDC_WAIT_MSG2                   1102
#define IDC_BUTTON1                     1103
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_CAMERA_LAYOUT                32771
#define ID_LAYOUT_1                     32772
#define ID_LAYOUT_2                     32773
#define ID_LAYOUT_SINGLE                32774
#define ID_LAYOUT_HORIZONTAL            32775
#define ID_LAYOUT_VERTICAL              32776
#define ID_LAYOUT_TRIPLE                32777
#define ID_LAYOUT_TRIPLE32778           32778
#define ID_LAYOUT_QUADRUPLE             32779
#define ID_CAMERA                       32780
#define ID_CAMERA_OVERHEAD              32780
#define ID_CAMERA_LEFTREAR              32781
#define ID_CAMERA_CENTRALREAR           32782
#define ID_CAMERA_RIGHTREAR             32783
#define ID_CAMERA_RIGHTSIDE             32784
#define ID_CAMERA_RIGHTFRONT            32785
#define ID_CAMERA_CENTRALFRONT          32786
#define ID_CAMERA_LEFTFRONT             32787
#define ID_CAMERA_LEFTSIDE              32788
#define ID_CAMERA_LIFTLEFT              32791
#define ID_CAMERA_LIFTRIGHT             32792
#define ID_STOREY_ONEUP                 32794
#define ID_STOREY_ONEDOWN               32795
#define ID_CAMERA_NAVIGATION            32797
#define ID_NAVIGATION_CCTV              32798
#define ID_NAVIGATION_WALK              32799
#define ID_NAVIGATION_GHOST             32804
#define ID_ACTION_PLAY                  32805
#define ID_ACTION_STOP                  32806
#define ID_ACTION_PAUSE                 32807
#define ID_ACTION_SPEEDUP               32808
#define ID_ACTION_SLOWDOWN              32809
#define ID_ACTION_NORMALPACE            32810
#define ID_VIEW_CHARACTER               32811
#define ID_CHARACTER_NOCOLOURCODING     32812
#define ID_CHARACTER_CURRENTWAITINGTIME 32813
#define ID_CHARACTER_EXPECTEDWAITINGTIME 32814
#define ID_CHARACTER_NOCOLOURCODING32815 32815
#define ID_FILE_OPENSIM                 32816
#define ID_FILE_SAVEIFC                 32817
#define ID_ACTION_RENDERTOAVI           32818
#define ID_ACTION_RENDER                32819
#define ID_ACTION_SAVESTILL             32820
#define ID_FILE_DOWNLOAD                32821
#define ID_VIEW_APPLOOK_WINDOWS_7       32822
#define ID_VIEW_APPLOOK_VS_2008         32823
#define ID_EDIT_FULLSCREEN              32824
#define ID_VIEW_FULLSCREEN              32825
#define ID_ACTION_PLAYSPECIAL           32826
#define ID_ACTION_REWIND                32829
#define ID_HUD_PINDOWN                  32830
#define ID_HUD_CLOSE                    32831
#define ID_HUD_PANEL                    32833
#define ID_HUD_CAPTION                  32834
#define ID_HUD_SELECT                   32835
#define ID_VIEW_ASPECT_WIN              32840
#define ID_VIEW_ASPECT_SCREEN           32841
#define ID_VIEW_ASPECT_16_9             32842
#define ID_VIEW_ASPECT_16_10            32843
#define ID_VIEW_ASPECT_4_3              32844
#define ID_VIEW_ASPECT_CUSTOM           32845
#define ID_VIEW_ASPECT                  32846
#define ID_STOREY                       32849
#define ID_STOREY_MENU                  32849
#define ID_SELCAMERA                    32850
#define ID_SELCAMERA_1                  32851
#define ID_SELCAMERA_2                  32852
#define ID_SELCAMERA_3                  32853
#define ID_SELCAMERA_4                  32854
#define ID_SELCAMERA_5                  32855
#define ID_SELCAMERA_6                  32856
#define ID_SELCAMERA_7                  32857
#define ID_SELCAMERA_8                  32858
#define ID_SELCAMERA_9                  32859
#define ID_SELCAMERA_10                 32860
#define ID_SELCAMERA_11                 32861
#define ID_SELCAMERA_12                 32862
#define ID_SELCAMERA_13                 32863
#define ID_SELCAMERA_14                 32864
#define ID_SELCAMERA_15                 32865
#define ID_SELCAMERA_16                 32866
#define ID_CAMERA_EXT_REAR              32867
#define ID_CAMERA_EXT_FRONT             32868
#define ID_CAMERA_EXT_SIDE              32879
#define ID_CAMERA_LIFT_MENU             32880
#define ID_CAMERA_LIFT                  32881
#define ID_FLOOR_CHANGEFLOOR            32882
#define ID_OTHER_REPORTBUG              32883
#define ID_REPORT_BUG                   32884
#define ID_VIEW_MATERIALS               32885
#define ID_REC_SCRIPT                   32888
#define ID_REC_RECORD                   32889
#define ID_REC_PLAY                     32890
#define ID_EDIT_SCRIPT                  32893
#define ID_EDIT_INSTANTRECORD           32894
#define ID_TMP_GROUP1                   32895
#define ID_TMP_GROUP2                   32896
#define ID_BUTTON4                      32897
#define ID_TMP_GROUP3                   32897
#define ID_CAMERA_GROUPRIGHT            32898
#define ID_CAMERA_GROUP_LEFT            32899
#define ID_SCENARIO_MENU                32900
#define ID_CAMERA_GROUP_MENU            32901
#define ID_CAMERA_GROUPLEFT             32903
#define ID_SELTENANCY                   32904
#define ID_TENANCY_MENU                 32905
#define ID_OTHER_FAILURE                32906
#define ID_FILE_SIMULATION              32907

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        364
#define _APS_NEXT_COMMAND_VALUE         32909
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           321
#endif
#endif
