#include "StdAfx.h"
#include "IFCScanner.h"

int temp__(int nTargetModel)
{
		BOOL bVal;
		int nVal;
		double dVal;
		int *hAggreg0, *hAggreg1, *hAggreg2, *hAggreg3, *hAggreg4, *hAggreg5, *hAggreg6, *hAggreg7, *hAggreg8, *hAggreg9, *hAggreg10, *hAggreg11, *hAggreg12, *hAggreg13, *hAggreg14, *hAggreg15, *hAggreg16, *hAggreg17, *hAggreg18;
		int hInstance0, hInstance1, hInstance2, hInstance3, hInstance4, hInstance5, hInstance6, hInstance7, hInstance8, hInstance9, hInstance10, hInstance11, hInstance12, hInstance13, hInstance14, hInstance15, hInstance16, hInstance17, hInstance18;



hInstance0 = sdaiCreateInstanceBN(nTargetModel, "IfcProductDefinitionShape");
if (!hInstance0) return NULL;
hAggreg1 = sdaiCreateAggrBN(hInstance0, "Representations");
hInstance2 = sdaiCreateInstanceBN(nTargetModel, "IfcShapeRepresentation");
hInstance3 = sdaiCreateInstanceBN(nTargetModel, "IfcGeometricRepresentationContext");
sdaiPutAttrBN(hInstance3, "ContextType", 10, "Model"); 
nVal = 3;  sdaiPutAttrBN(hInstance3, "CoordinateSpaceDimension", 7, &nVal); 
dVal = 0.000001; sdaiPutAttrBN(hInstance3, "Precision", 9, &dVal); 
hInstance4 = sdaiCreateInstanceBN(nTargetModel, "IfcAxis2Placement3D");
hInstance5 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg6 = sdaiCreateAggrBN(hInstance5, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg6, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg6, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg6, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance5, "Coordinates", 2, (void*)hAggreg6); 
sdaiPutAttrBN(hInstance4, "Location", 6, (void*)hInstance5); 
sdaiPutAttrBN(hInstance3, "WorldCoordinateSystem", 6, (void*)hInstance4); 
sdaiPutAttrBN(hInstance2, "ContextOfItems", 6, (void*)hInstance3); 
sdaiPutAttrBN(hInstance2, "RepresentationIdentifier", 10, "Body"); 
sdaiPutAttrBN(hInstance2, "RepresentationType", 10, "MappedRepresentation"); 
hAggreg3 = sdaiCreateAggrBN(hInstance2, "Items");
hInstance4 = sdaiCreateInstanceBN(nTargetModel, "IfcMappedItem");
hInstance5 = sdaiCreateInstanceBN(nTargetModel, "IfcRepresentationMap");
hInstance6 = sdaiCreateInstanceBN(nTargetModel, "IfcAxis2Placement3D");
hInstance7 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg8 = sdaiCreateAggrBN(hInstance7, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg8, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg8, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg8, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance7, "Coordinates", 2, (void*)hAggreg8); 
sdaiPutAttrBN(hInstance6, "Location", 6, (void*)hInstance7); 
sdaiPutAttrBN(hInstance5, "MappingOrigin", 6, (void*)hInstance6); 
hInstance6 = sdaiCreateInstanceBN(nTargetModel, "IfcShapeRepresentation");
hInstance7 = sdaiCreateInstanceBN(nTargetModel, "IfcGeometricRepresentationContext");
sdaiPutAttrBN(hInstance7, "ContextType", 10, "Model"); 
nVal = 3;  sdaiPutAttrBN(hInstance7, "CoordinateSpaceDimension", 7, &nVal); 
dVal = 0.000001; sdaiPutAttrBN(hInstance7, "Precision", 9, &dVal); 
hInstance8 = sdaiCreateInstanceBN(nTargetModel, "IfcAxis2Placement3D");
hInstance9 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg10 = sdaiCreateAggrBN(hInstance9, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg10, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg10, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg10, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance9, "Coordinates", 2, (void*)hAggreg10); 
sdaiPutAttrBN(hInstance8, "Location", 6, (void*)hInstance9); 
sdaiPutAttrBN(hInstance7, "WorldCoordinateSystem", 6, (void*)hInstance8); 
sdaiPutAttrBN(hInstance6, "ContextOfItems", 6, (void*)hInstance7); 
sdaiPutAttrBN(hInstance6, "RepresentationIdentifier", 10, "Body"); 
sdaiPutAttrBN(hInstance6, "RepresentationType", 10, "SurfaceModel"); 
hAggreg7 = sdaiCreateAggrBN(hInstance6, "Items");
hInstance8 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceBasedSurfaceModel");
hAggreg9 = sdaiCreateAggrBN(hInstance8, "FbsmFaces");
hInstance10 = sdaiCreateInstanceBN(nTargetModel, "IfcConnectedFaceSet");
hAggreg11 = sdaiCreateAggrBN(hInstance10, "CfsFaces");
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 10.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 10.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 10.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 10.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 10.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 10.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 10.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 10.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 10.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 10.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 10.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 10.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
sdaiPutAttrBN(hInstance10, "CfsFaces", 2, (void*)hAggreg11); 
sdaiAppend((int)hAggreg9, 6, (void*)hInstance10);
hInstance10 = sdaiCreateInstanceBN(nTargetModel, "IfcConnectedFaceSet");
hAggreg11 = sdaiCreateAggrBN(hInstance10, "CfsFaces");
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 740.268702; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 740.268702; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 740.268702; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 740.268702; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 740.268702; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 740.268702; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 740.268702; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 740.268702; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 740.268702; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 740.268702; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 740.268702; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 740.268702; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
sdaiPutAttrBN(hInstance10, "CfsFaces", 2, (void*)hAggreg11); 
sdaiAppend((int)hAggreg9, 6, (void*)hInstance10);
hInstance10 = sdaiCreateInstanceBN(nTargetModel, "IfcConnectedFaceSet");
hAggreg11 = sdaiCreateAggrBN(hInstance10, "CfsFaces");
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 1300.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 1300.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 1300.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 1300.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 1300.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 1300.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 1300.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 1300.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
hInstance12 = sdaiCreateInstanceBN(nTargetModel, "IfcFace");
hAggreg13 = sdaiCreateAggrBN(hInstance12, "Bounds");
hInstance14 = sdaiCreateInstanceBN(nTargetModel, "IfcFaceOuterBound");
hInstance15 = sdaiCreateInstanceBN(nTargetModel, "IfcPolyLoop");
hAggreg16 = sdaiCreateAggrBN(hInstance15, "Polygon");
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 1300.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 1300.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 2100.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 700.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 1300.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
hInstance17 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg18 = sdaiCreateAggrBN(hInstance17, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 1300.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg18, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance17, "Coordinates", 2, (void*)hAggreg18); 
sdaiAppend((int)hAggreg16, 6, (void*)hInstance17);
sdaiPutAttrBN(hInstance15, "Polygon", 2, (void*)hAggreg16); 
sdaiPutAttrBN(hInstance14, "Bound", 6, (void*)hInstance15); 
sdaiPutAttrBN(hInstance14, "Orientation", 10, ".T."); 
sdaiAppend((int)hAggreg13, 6, (void*)hInstance14);
sdaiPutAttrBN(hInstance12, "Bounds", 2, (void*)hAggreg13); 
sdaiAppend((int)hAggreg11, 6, (void*)hInstance12);
sdaiPutAttrBN(hInstance10, "CfsFaces", 2, (void*)hAggreg11); 
sdaiAppend((int)hAggreg9, 6, (void*)hInstance10);
sdaiPutAttrBN(hInstance8, "FbsmFaces", 2, (void*)hAggreg9); 
sdaiAppend((int)hAggreg7, 6, (void*)hInstance8);
sdaiPutAttrBN(hInstance6, "Items", 2, (void*)hAggreg7); 
sdaiPutAttrBN(hInstance5, "MappedRepresentation", 6, (void*)hInstance6); 
sdaiPutAttrBN(hInstance4, "MappingSource", 6, (void*)hInstance5); 
hInstance5 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianTransformationOperator3D");
hInstance6 = sdaiCreateInstanceBN(nTargetModel, "IfcCartesianPoint");
hAggreg7 = sdaiCreateAggrBN(hInstance6, "Coordinates");
dVal = 0.000000; sdaiAppend((int)hAggreg7, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg7, 9, (void*)(&dVal));
dVal = 0.000000; sdaiAppend((int)hAggreg7, 9, (void*)(&dVal));
sdaiPutAttrBN(hInstance6, "Coordinates", 2, (void*)hAggreg7); 
sdaiPutAttrBN(hInstance5, "LocalOrigin", 6, (void*)hInstance6); 
nVal = 1;  sdaiPutAttrBN(hInstance5, "Scale", 7, &nVal); 
sdaiPutAttrBN(hInstance4, "MappingTarget", 6, (void*)hInstance5); 
sdaiAppend((int)hAggreg3, 6, (void*)hInstance4);
sdaiPutAttrBN(hInstance2, "Items", 2, (void*)hAggreg3); 
sdaiAppend((int)hAggreg1, 6, (void*)hInstance2);
sdaiPutAttrBN(hInstance0, "Representations", 2, (void*)hAggreg1); 




return hInstance0;
}